package com.nexusglobal.rabbit.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Locale;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JPanel;

import org.springframework.stereotype.Component;
import java.awt.GridLayout;

@Component
public class AppView extends JFrame {
	
	
	//Autowired
	private LoginView loginView;
	private MainView mainView;
	
    //UI Components
	private JPanel pnlContent;
	
    //Global
    
    public AppView(final LoginView loginView, final MainView mainView) {
    	this.loginView = loginView;
    	this.mainView = mainView; 
    	
        buildUI();
    }

    private void buildUI() {
    	initComponents();
    	assignEventHandlers();
    	loadLoginView();
	}
    
    private void assignEventHandlers() {
		this.loginView.setOnLoginConsumer(this::onLogin);
	}
    
    private void loadLoginView() {
    	this.pnlContent.add(this.loginView);
    	refresh();
    }
    
    public void onLogin() {
    	this.pnlContent.removeAll();
    	this.pnlContent.add(this.mainView);
    }
    
    public void refresh() {
    	this.getContentPane().revalidate();
    	this.getContentPane().repaint();
    }
    
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	getContentPane().setLocale(Locale.ENGLISH);
    	
    	setMinimumSize(new Dimension(1024, 768));
    	setPreferredSize(new Dimension(1024, 768));
    	setSize(new Dimension(1024, 768));
    	getContentPane().setMinimumSize(new Dimension(1024, 768));
    	
    	pnlContent = new JPanel();
    	pnlContent.setMinimumSize(new Dimension(1024, 768));
    	pnlContent.setPreferredSize(new Dimension(1024, 768));
    	pnlContent.setSize(new Dimension(1024, 768));
    	getContentPane().add(pnlContent, BorderLayout.CENTER);
    	pnlContent.setLayout(new GridLayout(1, 0, 0, 0));
    	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      
        
                
        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	
}
